#!/bin/bash
gcc -g -Wall -Werror -pedantic simpleShell.c nonInteractiveShell.c currentInteractiveShell.c prompt.c strgen.c strmod.c buffer.c tokens.c path.c fork.c findCmd.c builtins.c init.c free.c exit.c environment.c -o hsh
